---
title: "Running openface in parallel"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Running openface in parallel}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#| message: false

# Load openac package
library(openac)

# Load parallelization packages
library(future)
library(furrr)
```

```{r}
# Check that openface is configured properly
check_openface()
```

```{r}
#| eval: false

# Find input video files to process
infiles <- list.files(
  path = "Z:/DynAMoS/Stimuli/Video",
  pattern = ".mp4$",
  full.names = TRUE,
  recursive = TRUE
)

# Create output CSV filenames

# # Replace directory path
outfiles <- gsub(
  pattern = "/Stimuli/Video/",
  replacement = "/Features/openface/",
  x = infiles
)

# # Replace file extension
outfiles <- gsub(
  pattern = ".mp4",
  replacement = ".csv",
  x = outfiles
)
```

```{r}
#| eval: false

# Set up parallelization
future::plan("multisession", workers = 4)

# Run extract_openface() on each file
furrr::future_walk2(
  .x = infiles,
  .y = outfiles,
  .f = openac::extract_openface,
  pdm = TRUE,
  wild = TRUE,
  multiview = TRUE
)
```

```{r}
# Check that the output files were created
list.files(
  path = "Z:/DynAMoS/Features/openface",
  pattern = ".csv$"
)
```

