# AC6 -- GP7 layer 2: real invocations of the wrapped tools.
#
# Every other test file mocks the `system2` boundary, which proves openac builds
# the right command but never that the command works. This file runs the tools
# for real, and is skipped wherever they are absent: on CRAN, on CI without the
# binaries, and on a contributor's machine that has only some of them. A skip
# here is the expected outcome, not a gap -- the mocked layer is what runs
# everywhere.
#
# Nothing in this file mocks anything: it uses the real `system2` and the real
# program resolution, so it is also the only check that openac's discovery finds
# a tool a user actually installed.

# `check_*()` warns when a tool is missing --- the right behavior for a user, and
# noise in a gate that is *expecting* the tool to be absent. The warning is
# suppressed here; the result never is.
have <- function(check) isTRUE(suppressWarnings(check()))

# Media is generated by ffmpeg rather than committed, so the repository carries
# no binary fixture and every input is built from a command visible right here.
real_wav <- function(rate = 44100, path = NULL, .env = parent.frame()) {
  if (is.null(path)) {
    path <- withr::local_tempfile(fileext = ".wav", .local_envir = .env)
  }
  ffmpeg(c(
    "-y", "-f", "lavfi", "-i", "sine=frequency=440:duration=1",
    "-ar", as.character(rate), "-ac", "1", "-c:a", "pcm_s16le",
    path
  ))
  path
}

real_video <- function(.env = parent.frame()) {
  path <- withr::local_tempfile(fileext = ".mp4", .local_envir = .env)
  ffmpeg(c(
    "-y", "-f", "lavfi", "-i", "testsrc=size=320x240:rate=10:duration=1",
    "-pix_fmt", "yuv420p",
    path
  ))
  path
}

# Whisper's gate. There is no exported `check_whisper()` -- audio.whisper is an
# R package rather than a binary openac resolves, and a model is a multi-hundred
# megabyte download this suite must never trigger. So the gate is: the package
# is installed AND a model file is already on disk, named by the environment
# variable. Absent either, the whisper test skips.
check_whisper <- function() {
  model <- Sys.getenv("OPENAC_WHISPER_MODEL", "")
  rlang::is_installed("audio.whisper") && nzchar(model) && file.exists(model)
}

# --- ffprobe -----------------------------------------------------------------

test_that("a path with a space and a $ survives the real shell round trip", {
  # AC2's other half. Every mocked test asserts what `system2()` was HANDED;
  # this asserts what the tools DID with it, which is the claim that matters and
  # which no mock can make.
  #
  # The failure it pins is measured, not imagined: before M13 the assemblers
  # interpolated `"` around the path, and `$dollar` expanded inside those double
  # quotes, so ffmpeg wrote -- and ffprobe was then asked for -- a DIFFERENT
  # file than the caller named. A space alone survived the old form, so this
  # needs the `$` to discriminate.
  skip_on_cran()
  skip_if(!have(check_ffprobe), "ffprobe is not installed")
  skip_if(!have(check_ffmpeg), "ffmpeg is needed to generate the input")

  dir <- withr::local_tempdir()
  path <- file.path(dir, "a space and $dollar.wav")

  # ffmpeg must WRITE to the hostile path...
  real_wav(path = path)
  expect_true(file.exists(path))

  # ...and ffprobe must READ the same one back, rather than erroring on a name
  # the shell mangled into something else.
  streams <- ffp_count_streams(path)
  expect_identical(unname(streams[["Audio"]]), 1L)
  expect_identical(unname(streams[["Video"]]), 0L)
})

# --- the hostile-name table (M15) --------------------------------------------
#
# AC1. The test above proves that ONE hostile name -- a space and a `$` --
# survives the round trip on whatever platform it runs on. It has only ever run
# on macOS: CI installs no external binaries, so `test-real-tools.R` skips on
# every runner including `windows-latest`. The table below generalizes it to the
# characters the two shells act on, so that a run on a real Windows host answers
# what `shQuote(type = "cmd")` actually leaves exposed there. `$` stays in the
# table AND above: the test above is M13's regression with its own history, this
# is the same name under a rule that covers seven others.
#
# One `test_that()` per entry, deliberately. An expectation failure aborts its
# own `test_that()` and no other, so a single run reports a verdict for every
# entry rather than stopping at the first mangled one -- and AC2 records the
# whole table, not its first row.
#
# The loop calls `test_that()` bare, from this file, so the harness's execution
# recorder attributes these tests here (M10: a test generated by a `helper-*.R`
# FUNCTION is attributed to the helper, and its real file reads as never run --
# a loop written in the test file itself is not that case).

for (hostile_case in names(hostile_names())) {
  hostile_name <- hostile_names()[[hostile_case]]

  test_that(paste0("a filename carrying ", hostile_case, " survives the real shell round trip"), {
    skip_on_cran()
    skip_if(!have(check_ffmpeg), "ffmpeg is needed to write the file")
    skip_if(!have(check_ffprobe), "ffprobe is needed to read it back")

    dir <- withr::local_tempdir()
    path <- file.path(dir, hostile_name)

    # The write path: ffmpeg must create the file openac NAMED.
    real_wav(path = path)

    # `list.files()` rather than `file.exists()`, because when the name openac
    # passed is not the name that landed, the failure has to say what did --
    # `%TEMP%` expanding leaves a real file under a different name, and an
    # existence check reports only that something is missing.
    expect_setequal(list.files(dir), hostile_name)

    # The read path is quoted at the same boundary, so ffprobe must find the
    # same file rather than erroring on a name the shell rewrote under it.
    streams <- ffp_count_streams(path)
    expect_identical(unname(streams[["Audio"]]), 1L)
    expect_identical(unname(streams[["Video"]]), 0L)
  })
}

test_that("ffprobe really reports the streams in a generated file", {
  skip_on_cran()
  skip_if(!have(check_ffprobe), "ffprobe is not installed")
  skip_if(!have(check_ffmpeg), "ffmpeg is needed to generate the input")

  streams <- ffp_count_streams(real_wav())

  expect_identical(unname(streams[["Audio"]]), 1L)
  expect_identical(unname(streams[["Video"]]), 0L)
})

# --- ffmpeg ------------------------------------------------------------------

test_that("ffmpeg really transcodes to the format openSMILE expects", {
  skip_on_cran()
  skip_if(!have(check_ffmpeg), "ffmpeg is not installed")
  skip_if(!have(check_ffprobe), "ffprobe is needed to verify the output")

  infile <- real_wav(rate = 16000)
  outfile <- file.path(withr::local_tempdir(), "prepped.wav")

  os_prep_audio(infile, outfile)

  expect_true(file.exists(outfile))
  expect_gt(file.size(outfile), 0)
  # The conversion is verified by the tool, not by the wrapper's own report.
  expect_true(os_check_audio(outfile))
})

test_that("a real ffmpeg failure really sets the status the wrapper reads", {
  # The layer-2 counterpart of test-tool-exit-status.R, and the one assertion
  # the mocked layer structurally cannot make. Every mocked test there proves
  # openac reacts correctly to a `status` attribute that `fake_nonzero_exit()`
  # puts there itself; none of them can show that a real failing ffmpeg sets
  # one at all. If it signalled failure some other way -- or exited 0 on an
  # unreadable input -- every mocked test would stay green while the wrapper
  # reported nothing, which is the shape of blindness M16 found in the mocked
  # installer suite.
  #
  # The input is a real file containing text rather than a nonexistent path:
  # a missing file would trip os_prep_audio()'s own `file.exists()` guard and
  # never reach ffmpeg, so the test would pass without exercising the status
  # path at all.
  skip_on_cran()
  skip_if(!have(check_ffmpeg), "ffmpeg is not installed")

  infile <- withr::local_tempfile(fileext = ".mp4")
  writeLines("this is not a media file", infile)
  outfile <- file.path(withr::local_tempdir(), "out.wav")

  err <- expect_error(
    suppressWarnings(os_prep_audio(infile, outfile)),
    class = "openac_tool_failed"
  )

  msg <- gsub("\\s+", " ", conditionMessage(err))
  expect_match(msg, basename(infile), fixed = TRUE)
  expect_match(msg, "ffmpeg exited with status")
  expect_false(file.exists(outfile))
})

test_that("aw_prep_audio really produces a file whisper accepts", {
  skip_on_cran()
  skip_if(!have(check_ffmpeg), "ffmpeg is not installed")
  skip_if(!have(check_ffprobe), "ffprobe is needed to verify the output")

  infile <- real_wav(rate = 44100)
  outfile <- file.path(withr::local_tempdir(), "prepped.wav")

  aw_prep_audio(infile, outfile)

  expect_true(aw_check_audio(outfile))
})

# --- openSMILE ---------------------------------------------------------------

test_that("openSMILE really extracts features that os_read() can read", {
  skip_on_cran()
  skip_if(!have(check_opensmile), "openSMILE is not installed")
  skip_if(!have(check_ffmpeg), "ffmpeg is needed to generate the input")
  skip_if(!have(check_ffprobe), "ffprobe is needed by os_check_audio()")

  config <- "egemaps/v02/eGeMAPSv02"
  skip_if(
    !(config %in% os_list_configs()),
    paste0("this openSMILE install has no ", config)
  )

  infile <- real_wav()
  aggfile <- file.path(withr::local_tempdir(), "agg.csv")

  os_extract(infile, aggfile = aggfile, config = config)

  expect_true(file.exists(aggfile))
  features <- os_read(aggfile)
  # The functionals output is one row; the reader's contract is what is checked.
  expect_identical(nrow(features), 1L)
  expect_true("name" %in% names(features))
  expect_gt(ncol(features), 2)
})

test_that("os_extract_dir really runs openSMILE over a directory", {
  skip_on_cran()
  skip_if(!have(check_opensmile), "openSMILE is not installed")
  skip_if(!have(check_ffmpeg), "ffmpeg is needed to generate the inputs")
  skip_if(!have(check_ffprobe), "ffprobe is needed by os_check_audio()")

  config <- "egemaps/v02/eGeMAPSv02"
  skip_if(
    !(config %in% os_list_configs()),
    paste0("this openSMILE install has no ", config)
  )

  indir <- withr::local_tempdir()
  for (name in c("one.wav", "two.wav")) {
    file.copy(real_wav(), file.path(indir, name))
  }
  aggdir <- file.path(withr::local_tempdir(), "agg")

  result <- os_extract_dir(indir, "wav", aggdir = aggdir, config = config)

  expect_identical(nrow(result), 2L)
  expect_true(all(result$success))
  expect_true(all(file.exists(result$aggfile)))
})

# --- OpenFace ----------------------------------------------------------------

test_that("OpenFace really extracts features that of_read() can read", {
  skip_on_cran()
  skip_if(!have(check_openface), "OpenFace is not installed")
  skip_if(!have(check_ffmpeg), "ffmpeg is needed to generate the input")

  infile <- real_video()
  outfile <- file.path(withr::local_tempdir(), "faces.csv")

  of_extract(infile, outfile)

  expect_true(file.exists(outfile))
  faces <- of_read(outfile)
  # A synthetic test pattern holds no face, so no row count is asserted --- what
  # is asserted is that OpenFace ran and wrote its documented column layout.
  expect_true(all(c("frame", "face_id", "timestamp") %in% names(faces)))
})

# --- whisper -----------------------------------------------------------------

test_that("whisper really transcribes a prepared wav", {
  skip_on_cran()
  skip_if(!have(check_whisper), "audio.whisper or a local model is missing")
  skip_if(!have(check_ffmpeg), "ffmpeg is needed to generate the input")
  skip_if(!have(check_ffprobe), "ffprobe is needed by aw_check_audio()")

  infile <- real_wav(rate = 16000)
  model <- aw_get_model(Sys.getenv("OPENAC_WHISPER_MODEL"))
  rdsfile <- file.path(withr::local_tempdir(), "out.rds")

  out <- aw_transcribe(infile, model = model, rdsfile = rdsfile)

  expect_true(file.exists(rdsfile))
  # A sine tone yields no meaningful speech, so the transcript's content is not
  # asserted --- only that whisper ran and returned a readable transcription.
  expect_true(is.data.frame(aw_read(out)))
})
